# Generated by Django 3.0.5 on 2020-04-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oga_app', '0002_item_item_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_pic',
            new_name='picture',
        ),
    ]
