# Generated by Django 3.0.5 on 2020-04-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oga_app', '0004_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
