# Generated by Django 3.0.5 on 2020-04-13 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oga_app', '0005_auto_20200413_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='added_on',
        ),
    ]
