# Generated by Django 3.0.5 on 2020-04-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oga_app', '0006_remove_item_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('l', 'large'), ('xl', 'x-large'), ('s', 'small'), ('m', 'medium')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
