# Generated by Django 3.0.5 on 2020-04-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oga_app', '0007_item_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('L', 'large'), ('XL', 'x-large'), ('S', 'small'), ('M', 'medium')], max_length=2),
        ),
    ]
