# Generated by Django 3.0.5 on 2020-04-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oga_app', '0008_auto_20200413_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
