# Generated by Django 3.0.5 on 2020-04-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oga_app', '0009_item_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=2),
        ),
    ]
