# Generated by Django 3.0.5 on 2020-04-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oga_app', '0010_auto_20200413_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1),
        ),
    ]
