# Generated by Django 3.0.5 on 2020-04-20 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oga_app', '0014_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
