# Generated by Django 3.0.5 on 2020-04-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oga_app', '0015_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_num',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
