# Generated by Django 3.0.5 on 2020-04-18 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oga_app', '0016_auto_20200418_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='order_owner',
        ),
    ]
