# Generated by Django 3.0.5 on 2020-04-18 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oga_app', '0017_auto_20200418_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_owner', to='oga_app.Order'),
        ),
    ]
