# Generated by Django 3.0.5 on 2020-04-18 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oga_app', '0018_auto_20200418_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
